version: "3.4"

services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      - POSTGRES_USER=achim
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=datenbank
      - PGDATA=/var/lib/postgresql/data/db-files/
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

  frontend:
    restart: always
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      - FLASK_APP=/app/app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SQLALCHEMY_DATABASE_URI=postgresql://achim:passw0rd@db/datenbank
    tty: true
    volumes:
      - ./frontend:/app
    depends_on:
      - db

  backend:
    restart: always
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      - FLASK_APP=/app/app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SQLALCHEMY_DATABASE_URI=postgresql://achim:passw0rd@db/datenbank
    tty: true
    volumes:
      - ./backend:/app
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    ports:
      - "4000:4000"

volumes:
  db-data:
